<?php

namespace App\Http\Requests\Pos;

use Illuminate\Validation\Rule;

class VenteRequest extends ApercuRequest
{
    /** @return array<string, mixed> */
    public function rules(): array
    {
        return parent::rules() + [
            'client_id' => ['nullable', 'integer', Rule::exists('clients', 'id')],
            // The two ways the counter takes money; their meaning is unchanged.
            'mode' => ['required', Rule::in(['especes', 'tpe'])],
            'encaisser' => ['required', 'boolean'],
            // One per sale attempt, generated by the till: a retried request
            // carries the same key and cannot sell twice.
            'cle' => ['required', 'string', 'uuid'],
        ];
    }
}
